dist: trusty
language: cpp
sudo: required

services:
  - docker

env:
  - BUILDER="docker.io/toanju/builder:28"
before_install:
  - docker pull $BUILDER

script:
  - docker run -v "$PWD":/workdir:Z --rm --name builder -dti $BUILDER /bin/bash
  - docker exec builder find . -regex '.*\.\(hh?\|cc?\|hpp\|cpp\)$' | xargs docker exec builder clang-format -i -style=file -fallback-style=llvm
  - docker exec builder git diff --exit-code
  - docker exec builder dnf -y copr enable bisdn/rofl
  - docker exec builder dnf -y copr enable bisdn/rofl-testing
  - docker exec builder make -C ./pkg/testing/rpm/ spec
  - docker exec builder dnf -y builddep ./pkg/testing/rpm/rofl-ofdpa.spec
  - docker exec builder ./autogen.sh
  - docker exec builder ./configure
  - docker exec builder make -j
